config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :notes, :categories

  root to:'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :notes, dependent: :destroy
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @notes = @category.notes #because of the associations in the model files we can call all notes in any specific category in this way.
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.owner_id = 2
    if @category.save
      flash[:alert] = 'Your new category has been successfully created.'
      redirect_to :action => 'index'
    else
      flash.now[:alert] = 'Error creating the new category, please try again!'
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:alert] = "Your updated category has been saved."
      redirect_to category_path
    else
      flash.now[:alert] = "Couldn't update your category, please try again or cancel!"
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:alert] = "Your category has been deleted successfully"
      redirect_to :action => 'index'
    else
      flash.now[:alert] = "We couldn't delete your category, please try again!"
      render 'show'
    end
  end

  private
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all.order("updated_at DESC") # Note here is referring to the model
  end

  def show
    @note = Note.find(params[:id])
    @category = Category.find(@note[:category_id])
  end

  def new
    @note = Note.new
    @categories = Category.all # Category here is referring to the model
    # @categories.order("name")
  end

  def create
    @note = Note.new(note_params)
    @note.owner_id = 1
    if @note.save
      flash[:alert] = "Your note has been saved"
      redirect_to :action => 'index'
    else
      flash.now[:alert] = "Error saving your new note, please try again!"
      render 'new'
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update_attributes(note_params)
      flash[:alert] = "Your updated note has been saved."
      redirect_to note_path
    else
      flash.now[:alert] = "Couldn't update your note, please try again or cancel!"
      render 'edit'
    end
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.destroy
      flash[:alert] = "Your note has been deleted successfully"
      redirect_to :action => 'index'
    else
      flash.now[:alert] = "We couldn't delete your note, please try again!"
      render 'show'
    end
  end

  private
  def note_params
    params.require(:note).permit(:title, :body, :category_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h1>Edit your category</h1>
<hr />
<%= form_for @category do |category| %>
  <p>
    <%= category.label :name %><br />
    <%= category.text_field :name %><br />
  </p>
  <p>
    <%= category.label :description %><br />
    <%= category.text_area :description %><br />
  </p>
  <p>
    <%= category.submit 'Edit category' %>
<% end %>
<hr />
<small><%= link_to 'Cancel', action: 'index' %></small>

app/views/categories/index.html.erb
<h1>This is a list of all catigories available:</h1>
<table>
  <td><small><%= link_to "Creae new category", new_category_path %></small></td>
  <td><small><%= link_to "View available notes", notes_path %></small></td>
</table>
<hr />
<ol>
<% @categories.each do |category| %>
  <li><%= link_to category[:name], category %><small> (<%= category[:created_at].strftime("%b %d. %Y") %>)</small></li>
<% end %>

app/views/categories/new.html.erb
<h1>Add a new category</h1>
<hr />
<%= form_for @category do |category| %>
  <p>
    <%= category.label :name %><br />
    <%= category.text_field :name %><br />
  </p>
  <p>
    <%= category.label :description %><br />
    <%= category.text_area :description %><br />
  </p>
  <p>
    <%= category.submit 'Add category' %>
<% end %>
<hr />
<small><%= link_to 'Cancel', action: 'index' %></small>

app/views/categories/show.html.erb
<h3><%= @category[:name] %></h3>
<small>
  <%= @category[:created_at].strftime("%b %d. %Y - %H:%M:%S") %>
  <% if @category[:created_at] != @category[:updated_at] %>
    <small> - updated on: <%= @category[:updated_at].strftime("%b %d. %Y - %H:%M:%S") %></small>
  <% end %>
</small>
<hr>
<table>
  <td><h3>Description:</h3></td>
  <td><p><%= @category[:description] %></p></td>
</table>
<ol>
<% if @notes.each do |note| %>
  <li><%= link_to note.title, note_path(:id => note.id) %></li>
<% end.empty? %>
  <p>Sorry, no notes are available in this category!</p>
<% end %>
</ol>
<hr />
<small> <%= link_to 'Edit category', action: 'edit' %> - <%= link_to 'Delete category and all notes related to it', @category, :method => :delete, data: { confirm: "Are you sure you want to delete this category with all notes related to it?\n\nOnce done you can\'t revoke this action!" } %> - <%= link_to 'Categories', action: 'index' %> - <%= link_to 'Notes', notes_path %></small>

app/views/home/index.html.erb
<h1> Welcome to S-Notes </h1>
<hr>
<h3>In this application I'm practicing working with rails to deliver a fullstack project</h3>
<p> To get started follow the link below</p>

<%= link_to 'Go to available notes', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <script>alert('<%= msg %>')</script>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit your note</h1>
<hr />
<%= form_for @note do |note| %>
  <p>
    <%= note.label :title %><br />
    <%= note.text_field :title %><br />
  </p>
  <p>
    <%= note.label :body %><br />
    <%= note.text_area :body %><br />
  </p>
  <p>
    <%= note.select :category_id, Category.all.collect{ |x| [x.name, x.id]}, { :include_blank => "Select a category"} %><br />
  </p>
  <p>
    <%= note.submit 'Edit note' %>
<% end %>
<hr />
<%= link_to 'Cancel', note_path %>

app/views/notes/index.html.erb
<h1> This is a list of all notes available: </h1>
<table>
  <td><small><%= link_to "Create new note", new_note_path %></small></td>
  <td><small><%= link_to "View abailable categories", categories_path %></small></td>
</table>
<hr />
<ol>
<% @notes.each do |note| %>
  <li><%= link_to note[:title], note %><small> (<%= note[:created_at].strftime("%b %d. %Y") %>)</small></li>
<% end %>
</ol>

app/views/notes/new.html.erb
<h1>Add a new note</h1>
<hr />
<%= form_for @note do |note| %>
  <p>
    <%= note.label :title %><br />
    <%= note.text_field :title %><br />
  </p>
  <p>
    <%= note.label :body %><br />
    <%= note.text_area :body %><br />
  </p>
  <p>
    <%= note.select :category_id, Category.all.order('name').collect{ |x| [x.name, x.id]}, { :include_blank => "Select a category"} %><br />
  </p>
  <p>
    <%= note.submit 'Add note' %>
<% end %>
<hr />
<small><%= link_to 'Cancel', action: 'index' %></small>

app/views/notes/show.html.erb
<h3><%= @note[:title] %></h3>
<small>
  <%= @note[:created_at].strftime("%b %d. %Y - %H:%M:%S") %>
  <% if @note[:created_at] != @note[:updated_at] %>
    <small> - updated on: <%= @note[:updated_at].strftime("%b %d. %Y - %H:%M:%S") %></small>
  <% end %>
</small>
<hr>
<table>
  <tr>
    <td><h3>Note Category:</h3></td>
    <td><p><%= link_to @category[:name],category_path(:id => @note.category_id) %></p></td>
  </tr>
</table>
<h3>Note Body:</h3>
<p><%= @note[:body] %></p>
<hr />
<small><%= link_to 'Edit note', action: 'edit' %> -
<%= link_to 'Delete note', @note, :method => :delete, data: { confirm: "Are you sure you want to delete this note?" } %> - <%= link_to 'Categories', categories_path %> - <%= link_to 'Notes', notes_path %></small>

app/views/users/index.html.erb
<h1> Add new users here </h1>